Repository Tech-With-Tim/API, pull requests merged in 2021-01, with the labels that each got.

#34 Validators
  utils/__init__.py
  utils/validators.py
Labels: enhancement

#36 Permission decorators
  api/models/user.py
  launch.py
  utils/__init__.py
  utils/decorators.py
Labels: enhancement

#35 Update README.md | Typos fixed
  README.md
Labels: documentation

#32 Add /guilds endpoints
  .github/workflows/lint-and-test.yml
  .pre-commit-config.yaml
  README.md
  api/app.py
  api/blueprints/auth/views/tokens.py
  api/blueprints/guilds/__init__.py
  api/blueprints/guilds/views/__init__.py
  api/blueprints/guilds/views/configs.py
  api/blueprints/guilds/views/guilds.py
  api/models/__init__.py
  api/models/guild.py
  api/models/guild_config.py
  api/models/token.py
  docs/README.md
  docs/_template.md
  docs/auth.md
  docs/auth/discord/callback.md
  docs/auth/discord/redirect.md
  docs/guilds.md
  launch.py
  tests/conftest.py
  tests/test_auth.py
  tests/test_guilds.py
  tests/test_index.py
  utils/validators.py
Labels: documentation, enhancement
